# Project Assignment - Part 1

### Roberto Pellungrini, Anna Monreale (October 8, 2020)

#### Introduction
In Part 1 of the project you are required to create and populate a database starting from .csv
files and perform different operations on it. In the following you can find a set of incremental
assignments, each one with a brief description of what you are required to produce and what
tools you can use for the task.

#### Build the datawarehouse
fact.csv is in the form (Id,gpu code,cpu code,ram code,time code,geo code,vendor code
,sales uds,sales currency) and it contains the main body of data: a fact table with sales
data of three different product lines: cpu, gpu and ram. Note that fields gpu code, cpu code,
ram code indicate the type of product: only one can have a non null value in a given row,
the other two are necessarily missing.
gpu.csv, cpu.csv and ram.csv are product dimensions. They can be linked to the main
fact table with the respective primary keys. The primary keys in these three dimension tables
are linked, respectively, to gpu code, cpu code, ram code in the fact table.
geo.csv time.csv vendor.csv are dimensions. They can be linked to the main fact
table with their primary keys.
The goal of the following assignments is to build in server apa.di.unipi.it the datawarehouse represented in Figure 1.

# Start

### Assignment 0
Create the database schema in Figure 1 using SQL Server Management Studio in server apa.di.unipi.it. The name of the database must be GroupIDHWMart (example: Group01HWMart)

In [ ]:
'''import pyodbc;
import re;

_haveDb=True;
_db = pyodbc.connect("Driver={SQL Server};Server=.;Trusted_Connection=yes;", autocommit=True);
_cursor = _db.cursor();
AvailableDbs = _cursor.execute("SELECT name FROM master.sys.databases");
_matches = [];

for i in AvailableDbs:
    print(i[0])
    if(re.compile("Group\d.*art$").match(i)):
        matches.append(i[0]);

DbName = "Group" + re.search("Group(\d.)",_matches[-1])[1] + "HWMart";

_cursor.execute('CREATE DATABASE ' + DbName);
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Ram_product]([Id] [int] IDENTITY(1,1) NOT NULL,[ram_code] [int] NOT NULL,[brand] [varchar](50) NOT NULL,[name] [varchar](50) NOT NULL,[memory] [varchar](50) NULL,[memory_type] [varchar](50) NOT NULL,[clock] [varchar](50) NULL,CONSTRAINT [PK_Ram_product] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Ram_sales]([Id] [int] IDENTITY(1,1) NOT NULL,[ram_code] [int] NOT NULL,[time_code] [int] NOT NULL,[geo_code] [int] NOT NULL,[vendor_code] [int] NULL,[sales_usd] [decimal](19,4) NOT NULL,[sales_currency] [char](6) NOT NULL,CONSTRAINT [PK_Ram_sales] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Gpu_product]([Id] [int] IDENTITY(1,1) NOT NULL,[gpu_code] [int] NOT NULL,[processor] [varchar](50) NOT NULL,[processor_manufacturer] [varchar](50) NOT NULL,[brand] [varchar](50) NULL,[memory] [varchar](10) NOT NULL,[memory_type] [varchar](10) NULL,CONSTRAINT [PK_Gpu_product] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Gpu_sales]([Id] [int] IDENTITY(1,1) NOT NULL,[gpu_code] [int] NOT NULL,[time_code] [int] NOT NULL,[geo_code] [int] NOT NULL,[vendor_code] [int] NULL,[sales_usd] [decimal](19,4) NOT NULL,[sales_currency] [char](6) NOT NULL,CONSTRAINT [PK_Gpu_sales] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Cpu_product]([Id] [int] IDENTITY(1,1) NOT NULL,[Cpu_code] [int] NOT NULL,[brand] [varchar](50) NOT NULL,[series] [varchar](50) NULL,[name] [varchar](50) NOT NULL,[socket] [varchar](50) NOT NULL,[n_cores] [int] NOT NULL,CONSTRAINT [PK_Cpu_product] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Cpu_sales]([Id] [int] IDENTITY(1,1) NOT NULL,[Cpu_code] [int] NOT NULL,[time_code] [int] NOT NULL,[geo_code] [int] NOT NULL,[vendor_code] [int] NULL,[sales_usd] [decimal](19,4) NOT NULL,[sales_currency] [char](6) NOT NULL,CONSTRAINT [PK_Gpu_sales] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Geography]([Id] [int] IDENTITY(1,1) NOT NULL,[geo_code] [int] NOT NULL,[continent] [varchar](20) NOT NULL,[country] [varchar](100) NOT NULL,[region] [int] NULL,[currency] [char](10) NOT NULL, CONSTRAINT [PK_Geography] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Vendor]([Id] [int] IDENTITY(1,1) NOT NULL,[vendor_code] [int] , [brand] [varchar](100) NOT NULL, CONSTRAINT [PK_Vendor] PRIMARY KEY CLUSTERED ([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")
_cursor.execute("USE ["+DbName+"] CREATE TABLE [dbo].[Time]([time_id] [int] IDENTITY(1,1) NOT NULL,[year] [int] NOT NULL,[month] [int] NOT NULL,[day] [int] NOT NULL,[week] [char](10) NOT NULL,[quarter] [char](4) NOT NULL,[day_of_week] [varchar](10) NOT NULL, CONSTRAINT [PK_Time] PRIMARY KEY CLUSTERED ([time_id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]")


'''

In [ ]:
USE [Group26HWMart]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


USE [Group26HWMart]
GO
/****** Object:  Table [group26].[vendor]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[vendor]') AND type in (N'U'))
DROP TABLE [group26].[vendor]
GO

CREATE TABLE [group26].[vendor](
    [vendor_code] [int] NULL,
    [name] [varchar](50) NULL
) ON [PRIMARY]
GO

/****** Object:  Table [group26].[time]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[time]') AND type in (N'U'))
DROP TABLE [group26].[time]
GO

CREATE TABLE [group26].[time](
    [time_id] [int] NULL,
    [year] [int] NULL,
    [month] [int] NULL,
    [day] [int] NULL,
    [week] [int] NULL,
    [quarter] [char](2) NULL,
    [day_of_week] [varchar](10) NULL
) ON [PRIMARY]
GO

USE [Group26HWMart]
GO

/****** Object:  Table [group26].[ram_sales]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[ram_sales]') AND type in (N'U'))
DROP TABLE [group26].[ram_sales]
GO

CREATE TABLE [group26].[ram_sales](
    [ram_code] [int] NULL,
    [time_code] [int] NULL,
    [geo_code] [int] NULL,
    [vendor_code] [int] NULL,
    [sales_usd] [varchar](50) NULL,
    [sales_currency] [varchar](50) NULL
) ON [PRIMARY]
GO

USE [Group26HWMart]
GO

/****** Object:  Table [group26].[ram_product]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[ram_product]') AND type in (N'U'))
DROP TABLE [group26].[ram_product]
GO

CREATE TABLE [group26].[ram_product](
    [ram_code] [int] NULL,
    [brand] [varchar](50) NULL,
    [name] [varchar](50) NULL,
    [memory] [int] NULL,
    [memory_type] [varchar](50) NULL,
    [clock] [int] NULL
) ON [PRIMARY]
GO

USE [Group26HWMart]
GO

/****** Object:  Table [group26].[gpu_sales]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[gpu_sales]') AND type in (N'U'))
DROP TABLE [group26].[gpu_sales]
GO

CREATE TABLE [group26].[gpu_sales](
    [gpu_code] [int] NULL,
    [time_code] [int] NULL,
    [geo_code] [int] NULL,
    [vendor_code] [int] NULL,
    [sales_usd] [varchar](50) NULL,
    [sales_currency] [varchar](50) NULL
) ON [PRIMARY]
GO

USE [Group26HWMart]
GO

/****** Object:  Table [group26].[gpu_product]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[gpu_product]') AND type in (N'U'))
DROP TABLE [group26].[gpu_product]
GO

CREATE TABLE [group26].[gpu_product](
    [gpu_code] [int] NULL,
    [processor] [varchar](50) NULL,
    [processor_manufacture] [varchar](50) NULL,
    [brand] [varchar](50) NULL,
    [memory] [float] NULL,
    [memory_type] [varchar](50) NULL
) ON [PRIMARY]
GO

USE [Group26HWMart]
GO

/****** Object:  Table [group26].[geograpgy]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[geography]') AND type in (N'U'))
DROP TABLE [group26].[geography]
GO

CREATE TABLE [group26].[geography](
    [geo_code] [int] NULL,
    [continent] [varchar](50) NULL,
    [country] [varchar](50) NULL,
    [region] [varchar](50) NULL,
    [currency] [varchar](50) NULL
) ON [PRIMARY]
GO

USE [Group26HWMart]
GO

/****** Object:  Table [group26].[cpu_sales]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[cpu_sales]') AND type in (N'U'))
DROP TABLE [group26].[cpu_sales]
GO

CREATE TABLE [group26].[cpu_sales](
    [cpu_code] [int] NULL,
    [time_code] [int] NULL,
    [geo_code] [int] NULL,
    [vendor_code] [int] NULL,
    [sales_usd] [varchar](50) NULL,
    [sales_currency] [varchar](50) NULL
) ON [PRIMARY]
GO

USE [Group26HWMart]
GO

/****** Object:  Table [group26].[cpu_product]  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[group26].[cpu_product]') AND type in (N'U'))
DROP TABLE [group26].[cpu_product]
GO

CREATE TABLE [group26].[cpu_product](
    [cpu_code] [int] NULL,
    [brand] [varchar](50) NULL,
    [series] [varchar](50) NULL,
    [name] [varchar](50) NULL,
    [n_cores] [int] NULL,
    [socket] [varchar](50) NULL
) ON[primary]
GO

### Assignment 1
Write a python program that splits fact.csv into three separate fact tables, one for each line of products: cpu, gpu and ram. Write your program using only basic python functionalities (the use of the pandas library is forbidden).

In [ ]:
import threading
import pyodbc
import csv

Fact_Gpu=[]
Fact_Cpu=[]
Fact_Ram=[]

server = 'tcp:apa.di.unipi.it'
username = 'group26' 
password = 'l3wwh' 
connectionString = 'DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';UID='+username+';PWD='+ password


_db = pyodbc.connect(connectionString,autocommit=True)
_cursor = _db.cursor()

db = pyodbc.connect(connectionString,autocommit=True)
cursor = db.cursor()

__db = pyodbc.connect(connectionString,autocommit=True)
__cursor = __db.cursor()


cursor.execute("DELETE FROM [Group26HWMart].[group26].[ram_sales]")
_cursor.execute("DELETE FROM [Group26HWMart].[group26].[gpu_sales]")
__cursor.execute("DELETE FROM [Group26HWMart].[group26].[cpu_sales]")


def SetFactTables():
        print("adding fact datas to fact tables")
        print('ram size: ', len(Fact_Ram))
        print('gpu size: ', len(Fact_Gpu))
        print('cpu size: ', len(Fact_Cpu))
        def _setRam():
            j = 1
            cursor.fast_executemany = True
            tmp = 0
            size = int(len(Fact_Ram)/200000)
            for l in range(size):
                temp = (l + 1)*200000
                cursor.executemany("INSERT INTO [Group26HWMart].[group26].[ram_sales] VALUES (?, ?, ?, ?, ?, ?)", Fact_Ram[tmp:temp])
                tmp = temp
                print('thread ram ', j)
                j = j + 1
            cursor.executemany("INSERT INTO [Group26HWMart].[group26].[ram_sales] VALUES (?, ?, ?, ?, ?, ?)", Fact_Ram[tmp:])
            cursor.close()
            print("Ram Fact table splited!")
        
        def _setCpu():
            j = 1
            __cursor.fast_executemany = True
            tmp = 0
            size = int(len(Fact_Cpu)/200000)
            for l in range(size):
                temp = (l + 1)*200000
                __cursor.executemany("INSERT INTO [Group26HWMart].[group26].[cpu_sales] VALUES (?, ?, ?, ?, ?, ?)", Fact_Cpu[tmp:temp])
                tmp = temp
                print('thread cpu ', j)
                j = j + 1
            __cursor.executemany("INSERT INTO [Group26HWMart].[group26].[cpu_sales] VALUES (?, ?, ?, ?, ?, ?)", Fact_Cpu[tmp:])
            __cursor.close()
            print("Cpu Fact table splited!")

        def _setGpu():
            j = 1
            _cursor.fast_executemany = True
            tmp = 0
            size = int(len(Fact_Gpu)/200000)
            for l in range(size):
                temp = (l + 1) * 200000
                _cursor.executemany("INSERT INTO [Group26HWMart].[group26].[gpu_sales] VALUES (?, ?, ?, ?, ?, ?)", Fact_Gpu[tmp:temp])
                tmp = temp
                print('thread gpu ', j)
                j = j + 1
            _cursor.executemany("INSERT INTO [Group26HWMart].[group26].[gpu_sales] VALUES (?, ?, ?, ?, ?, ?)", Fact_Gpu[tmp:])
            _cursor.close()
            print("Gpu Fact table splited!")

        a=threading.Thread(target=_setRam)
        b=threading.Thread(target=_setGpu)
        c=threading.Thread(target=_setCpu)

        a.start()
        b.start()
        c.start()
        
        a.join()
        b.join()
        c.join()

#TASK NUMBER 1 : SPLIT FACT TABLES
def SplitFactTables():
    _reader = open("fact.csv")
    print("Splitting Fact Tables...")
    for row in csv.DictReader(_reader):
        if row["gpu_code"] not in (None, ''):
            Fact_Gpu.append((int(float(row["gpu_code"])),int(row["time_code"]), int(row["geo_code"]), int(row["vendor_code"]), float(row["sales_uds"]), row["sales_currency"] ))
            
        elif row["ram_code"] not in (None, ''):
            Fact_Ram.append((int(float(row["ram_code"])),int(row["time_code"]), int(row["geo_code"]), int(row["vendor_code"]), float(row["sales_uds"]), row["sales_currency"] ))

        elif row["cpu_code"] not in (None, ''):
            Fact_Cpu.append((int(float(row["cpu_code"])),int(row["time_code"]), int(row["geo_code"]), int(row["vendor_code"]), float(row["sales_uds"]), row["sales_currency"] ))
    SetFactTables()

    
    
SplitFactTables()

### Assignment 2
Write a Python program that populates the database GroupIDHWMart with the
three fact tables you obtained from the previous assignments and with the necessary
linked dimensions described in the remaining .csv files. Note that in Time table the
values of the attributes day of week and quarter should be derived from the date.
Indicate each quarter with the values: Q1, Q2, Q3, Q4. While for each day of week
indicate each day with its proper name (“Monday”, “Tuesday”, etc.).

In [ ]:
import csv
import pyodbc
import datetime


server = 'tcp:apa.di.unipi.it'
username = 'group26' 
password = 'l3wwh' 
connectionString = 'DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';UID='+username+';PWD='+ password


_db = pyodbc.connect(connectionString,autocommit=True)
_cursor = _db.cursor()

_cursor.fast_executemany = True



gpu_products = open('gpu.csv', 'r')
gpu_products_list = []
for row in csv.DictReader(gpu_products):
    gpu_products_list.append((int(row['gpu_code']), row['processor'], row['processor_manufacturer'], row['brand'], float(row['memory']), row['memory_type']))
gpu_products.close()
_cursor.executemany("INSERT INTO [Group26HWMart].[group26].[gpu_product] VALUES (?, ?, ?, ?, ?, ?)", gpu_products_list)
gpu_products_list = None
print('done1')

cpu_products = open('cpu.csv', 'r')
cpu_products_list = []
for row in csv.DictReader(cpu_products):
    cpu_products_list.append((int(row['cpu_code']), row['brand'], row['series'], row['name'], int(row['n_cores']), row['socket']))
cpu_products.close()
_cursor.executemany("INSERT INTO [Group26HWMart].[group26].[cpu_product] VALUES (?, ?, ?, ?, ?, ?)", cpu_products_list)
cpu_products_list = None
print('done2')

ram_product = open('ram.csv', 'r')
ram_product_list = []
for row in csv.DictReader(ram_product):
    ram_product_list.append((int(row['ram_code']), row['brand'], row['name'], float(row['memory']), row['memory_type'], int(row['clock'])))
ram_product.close()
_cursor.executemany("INSERT INTO [Group26HWMart].[group26].[ram_product] VALUES (?, ?, ?, ?, ?, ?)", ram_product_list)
ram_product_list = None
print('done3')

weekDays = ("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")
quarter = ['Q1', 'Q2', 'Q3', 'Q4']
time_file = open('time.csv')
time_list = []
for row in csv.DictReader(time_file):
    time_list.append((int(row['time_code']), int(row['year']), int(row['month']), int(row['day']), int(row['week']), quarter[(int(row['month'])-1) // 3], weekDays[datetime.date(int(row['year']), int(row['month']), int(row['day'])).weekday()]))
_cursor.executemany("INSERT INTO [Group26HWMart].[group26].[time] VALUES (?, ?, ?, ?, ?, ?, ?)", time_list)
time_file.close()
time_list = None
print('done4')

geography = open('geography.csv')
for row in csv.DictReader(geography):
    _cursor.execute("INSERT INTO [Group26HWMart].[group26].[geography] VALUES (?, ?, ?, ?, ?)", (int(row['geo_code']), row['continent'], row['country'], row['region'], row['currency']))
geography.close()
print('done5')

vendor = open('vendor.csv')
for row in csv.DictReader(vendor):
    _cursor.execute("INSERT INTO [Group26HWMart].[group26].[vendor] VALUES (?, ?)", (int(row['vendor_code']), row['name']))
vendor.close()
print('done6')

# Finish Part 1

#

# Project Assignment - Part 2

### Introduction
In Part 2 of the project you are required to answer some business questions on the database
you created in Part 1. Solve the exercises using Sequel Server Integration Services (SSIS)
with computation on client side (i.e., do not use any sql command, only standard SSIS
nodes). Each group has to solve only three assignments. Look at the section with your
groupid to find what assignments you need to do. Deliver your project with all the required
packages in a single .zip folder, named LDS Part2 groupid.zip.

## Groups from 17 to 26

### Assignment 0
For every region of Germany, the brand of ram ordered by sales

### Assignment 1
For every brand of gpu, calculate the ratio between sales during weekdays and sales
during the weekend.

### Assignment 2
Calculate which type of product, cpu, gpu or ram, yields the most sales for each
continent.